"""add_shareable_link_to_interview_config

Revision ID: 7161ddf73ccd
Revises: 8ea50fe6fc24
Create Date: 2025-09-07 23:55:17.533649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7161ddf73ccd'
down_revision = '8ea50fe6fc24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_configs', sa.Column('shareable_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_configs', 'shareable_link')
    # ### end Alembic commands ###

