"""add_user_id_to_interview_sessions

Revision ID: 8ea50fe6fc24
Revises: 39a27af4edd4
Create Date: 2025-09-07 01:32:35.174442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea50fe6fc24'
down_revision = '39a27af4edd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'user_id')
    # ### end Alembic commands ###

